### ISSUE TITLE
Connection of the SFM3200

### ISSUE THREAD

**Issue by Marower** [lauriaclarke/SFM3X00#6]
Hi,
please, can you describe the connection of the sensor. I have SFM3200 with the same cable as on your picture. 
I'm confused with its colours. According to datasheet (https://sensirion.com/media/documents/70FC8320/62962251/GF_DS_SFM3200.pdf):
White is SDA
Yellow - GND
Black - VCC
Red - SCK
Is it correct?
Kind regard,

**Comment by RobertLRead** [comment]
The datasheet is correct. I'm not sure what cable you are using, but in a perfect world you could test the I2C connection on a breadboard.  Personally, I prefer to arrange the cables to use what I consider to be "conventional" colors (RED = VCC, Black = GND, Yellow = SCL:. Blue = SDA). (This is the color code used by Sparkfun Quiic cables: [https://www.sparkfun.com/products/14425](https://www.sparkfun.com/products/14425)). 

However, if you already have the cable connection to the sensor, you are stuck with the colors as they come. What I would do is make a color map based on the datasheet (this maybe what you have already done in this issue that you opened. above.) Then I would test it on a breadboard, possible using an I2C scanner first, and then using the code in this library.

Note that the Sensirion sensors are 5V, not 3.3V; they won't work at 3.3V. You may need a logic level shift depending on what microcontroller you are attempting to use.

Let me know if that answers your question or if I can help in any other way.

**Comment by Marower** [comment]
Thank you. 
My cable is identical as that on picture [SFM3200andSFM3400.jpg](https://github.com/PubInv/SFM3X00/blob/master/SFM3200andSFM3400.jpg) from your repository.
I also preferred standard colors, this is very confusing.
